service: serverless-app

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: process.env.REGION

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

package:
  individually: true
  excludeDevDependencies: false

functions:
  register:
    handler: dist/functions/register.handler
    events:
      - http:
          path: serverless-app/auth/register
          method: POST

  login:
    handler: dist/functions/login.handler
    events:
      - http:
          path: serverless-app/auth/login
          method: POST
  
  verify:
    handler: dist/functions/verify.handler
    events:
      - http:
          path: serverless-app/auth/verify
          method: POST
  
  createLink:
    handler: dist/functions/link/createLink.handler
    events:
      - http:
          path: serverless-app/link/createLink
          method: POST
  
  deleteLink:
    handler: dist/functions/link/deleteLink.handler
    events:
      - http:
          path: serverless-app/link/deleteLink
          method: POST

  manageLinks:
    handler: dist/functions/link/manageLinks.handler
    events:
      - http:
          path: serverless-app/link/manageLinks
          method: POST

  useLink:
    handler: dist/functions/link/useLink.handler
    events:
      - http:
          path: serverless-app/link/useLink
          method: POST