service: serverless-app

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-central-1
  deploymentBucket:
    name: sls-app-bucket
  role: arn:aws:iam::019607412348:role/function-with-full-access

configValidationMode: error

plugins:
  - serverless-plugin-include-dependencies
  - serverless-plugin-common-excludes

package:
  individually: true
  excludeDevDependencies: false

functions:
  register:
    handler: dist/functions/register.handler
    events:
      - http:
          path: auth/register
          method: POST

  login:
    handler: dist/functions/login.handler
    events:
      - http:
          path: auth/login
          method: POST
  
  verify:
    handler: dist/functions/verify.handler
    events:
      - http:
          path: auth/verify
          method: POST
  
  createLink:
    handler: dist/functions/link/createLink.handler
    events:
      - http:
          path: link/createLink
          method: POST
  
  deactivateLink:
    handler: dist/functions/link/deactivateLink.handler
    events:
      - http:
          path: link/deactivateLink
          method: POST

  manageLinks:
    handler: dist/functions/link/manageLinks.handler
    events:
      - http:
          path: link/manageLinks
          method: POST

  useLink:
    handler: dist/functions/link/useLink.handler
    events:
      - http:
          path: link/useLink/{alias}
          method: POST